# Generated by Django 2.0.9 on 2018-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=20)),
                ('budget', models.IntegerField()),
                ('contact_person', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resource', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.IntegerField()),
                ('client_details', models.TextField()),
                ('target_date', models.DateField()),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
