# Generated by Django 2.0.9 on 2018-10-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contact_person',
        ),
    ]
